#!/bin/bash
# Prisma Schema Merger (Shell Script)
# Alternative to Node.js version - combines schema files in order

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCHEMA_DIR="$SCRIPT_DIR/../schema"
OUTPUT_FILE="$SCRIPT_DIR/../schema.prisma"

echo "🔄 Merging Prisma schema files..."
echo ""

# Create output file with header
cat > "$OUTPUT_FILE" << 'EOF'
// Enterprise Surgical EHR - Core Database Schema
// PostgreSQL with Prisma ORM
// This file is auto-generated by merge-schema script
// DO NOT EDIT DIRECTLY - Edit files in schema/ directory instead
//
// Generated: $(date)

EOF

# Merge files in order
for file in base.prisma foundation.prisma rbac.prisma password-history.prisma patient.prisma patient-intake.prisma consultation-request.prisma patient-lifecycle-transition.prisma consultation.prisma appointment.prisma procedure-plan.prisma orders.prisma prescription.prisma emr.prisma theater.prisma medical_records.prisma consent.prisma billing.prisma inventory.prisma audit.prisma; do
  file_path="$SCHEMA_DIR/$file"
  
  if [ ! -f "$file_path" ]; then
    echo "⚠️  Warning: $file not found, skipping..."
    continue
  fi
  
  echo "✅ Merging: $file"
  
  # Add section header
  echo "" >> "$OUTPUT_FILE"
  echo "// ============================================================================" >> "$OUTPUT_FILE"
  echo "// ${file^^} (${file%.prisma} | tr '[:lower:]' '[:upper:]')" >> "$OUTPUT_FILE"
  echo "// Source: schema/$file" >> "$OUTPUT_FILE"
  echo "// ============================================================================" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
  
  # Append file content
  cat "$file_path" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
done

echo ""
echo "✨ Successfully merged schema files into schema.prisma"
echo "📄 Output: $OUTPUT_FILE"
echo ""

