/**
 * Generate Consent Use Case
 * 
 * Application layer use case for generating a consent from a template.
 * This encapsulates the business logic and orchestrates domain services.
 */

import { Injectable, Logger, NotFoundException, ForbiddenException } from '@nestjs/common';
import { IConsentRepository } from '../../domain/interfaces/consent-repository.interface';
import { PDFProcessor } from '../../domain/interfaces/pdf-processor.interface';
import { ConsentStateMachine } from '../../domain/services/consent-state-machine.domain.service';
import { Consent, ConsentStatus } from '../../domain/entities/consent.entity';

export interface GenerateConsentRequest {
  templateId: string;
  patientId: string;
  consultationId?: string;
  placeholderValues: Record<string, string>;
  userId: string;
}

@Injectable()
export class GenerateConsentUseCase {
  private readonly logger = new Logger(GenerateConsentUseCase.name);

  constructor(
    private readonly consentRepository: IConsentRepository,
    private readonly pdfProcessor: PDFProcessor,
    private readonly stateMachine: ConsentStateMachine,
  ) {}

  async execute(request: GenerateConsentRequest): Promise<Consent> {
    this.logger.log(`Generating consent for patient ${request.patientId} from template ${request.templateId}`);

    // 1. Validate template exists and get PDF
    // This would be done by a template repository/service
    // For now, we assume it's validated upstream

    // 2. Load template PDF
    // This would be done by a template service
    // For now, we assume the PDF buffer is available

    // 3. Parse placeholders
    // This would be done by the template service
    // For now, we use the provided placeholderValues

    // 4. Merge placeholders into PDF
    // This is done by the PDF processor

    // 5. Create consent entity
    const consent = new Consent(
      '', // ID will be generated by repository
      request.templateId,
      request.patientId,
      request.consultationId || null,
      ConsentStatus.DRAFT,
      request.userId,
      new Date(),
    );

    // 6. Save consent
    const savedConsent = await this.consentRepository.create(consent);

    this.logger.log(`Consent ${savedConsent.id} generated successfully`);

    return savedConsent;
  }
}





